### ISSUE TITLE
Admin can't login

### ISSUE THREAD

**Issue by N-Upchurch** [navanchauhan/isso_ynh#11]
### Describe the bug

When attempting to login as admin, nothing happens at all.

### Context

- Hardware: VPS bought online
- YunoHost version: 11.2.23
- I have access to my server: Through SSH | through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 
- Using, or trying to install package version/branch: 0.13.0~ynh3

### Steps to reproduce

1. Install isso
2. Attempt to log in with password as configured during installation

### Expected behavior
Nothing happens except maybe a refresh.

**Comment by ericgaspar** [comment]
you need to connect with your ynh admin username.

**Comment by N-Upchurch** [comment]
@ericgaspar  What do you mean by this? My admin user does have access to Isso admin in groups and permissions. Can you explain further?
