### ISSUE TITLE
Isso web page not working anymore

### ISSUE THREAD

**Issue by blogdemoi** [navanchauhan/isso_ynh#4]
### Describe the bug

*Opening the isso page from the Yunohost administration page doesn't work anymore, it worked a few days ago*

### Context

- Hardware: *Raspberry Pi at home / Internet Cube with VPN*
- YunoHost 11.0.9.14 (stable)
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using: 0.13.0~ynh1

### Steps to reproduce

- *If you used the webadmin, please perform the equivalent command from the CLI first.*
- *If the error occurs in your browser, explain what you did:*
   1. *Go to https://isso.xxx.org/js/embed.min.js
   2.. *See error* Please see what I have on the page: https://arnauld.org/zerobin/?33b0d3bbcfa4ba47#EiRvhkWK6T3izq6nY74VoZjycXQ733VkV2q5K8RkYKPa

### Expected behavior

I expect to find the isso page

However I can still receive comments in my e-mails and approve or delete them.

Thank you.

**Comment by navanchauhan** [comment]
Noted

**Comment by navanchauhan** [comment]
Will be fixed by #8
